version: '3'
services:
  web:
    container_name: Ticket_Management
    build: ./ticket-management
    labels:
        SERVICE_80_NAME: Ticket_Management
        SERVICE_TAG: TicketManagement
    depends_on:
      - db
  db:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"