version: "3"
services:
    web:
        container_name: Ticket-Management
        build: ./ticket-management
        labels: 
            SERVICE_80_NAME: Ticket-Management   
            SERVICE_TAG: TicketManagement
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        ports:
            - "1443:1433"
        environment:
            SA_PASSWORD: "Test@123"
            ACCEPT_EULA: "Y"
