version: "3"
services:
    web:
        container_name: Ticket-Management
        build: ticket-management/
        environment: 
            SERVICE_NAME: auth    
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        ports:
            - "1443:1433"
        environment:
            SA_PASSWORD: "Test@123"
            ACCEPT_EULA: "Y"
