version: '3'
services:
  web:
    container_name: Ticket-Management
    build: ./ticket-management
    labels:
        SERVICE_80_NAME: Ticket-Management
        SERVICE_TAG: TicketManagement 
    depends_on:
      - mongo
  mongo:
    image: mvertes/alpine-mongo
    volumes :
       - "/data/resolute-ticket-management:/var/lib/mongodb"