version: '3'
services:
  web:
    container_name: ticket-management
    build: ./ticket-management
    labels:
        SERVICE_80_NAME: ticket-management
        SERVICE_TAG: ticketmanagement 
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - "/machine_config:/app/machine_config"
  mongo:
    image: mvertes/alpine-mongo
    volumes :
      - "/data/resolute-ticket-management:/var/lib/mongodb"
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  scheduler:
    container_name: analytics-scheduler
    build: ./AnalyticsScheduler
        
